- hosts: localhost
  name: create a new EC2 instance
  connection: local
  gather_facts: False
  roles:
    - launch_ec2

- hosts: newboxes
  name: setup
  user: ubuntu
  gather_facts: true
  roles:
    - { role: packages }
    - { role: mount_opt, data_device: /dev/xvdf }
    - { role: ec2 }

- include: configure.yml hosts=newboxes
