---
- name: set postgres password
  become: yes
  become_user: postgres
  postgresql_user: name=postgres password={{ pg_pass }}
  
- name: determine postgres directory
  shell: ls /etc/postgresql
  register: postgres_version

- name: configure md5 security
  become: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/{{ postgres_version.stdout }}/main/pg_hba.conf group=postgres owner=postgres backup=yes

- name: restart postgres server
  become: yes
  service: name=postgresql enabled=yes state=restarted

- name: create pg hydra database
  postgresql_db: name={{ hydra_db }} state=present login_user=postgres login_password={{ pg_pass }}

- name: add pg hydra user
  postgresql_user: db={{ hydra_db }} name={{ hydra_pg_user }} password={{ hydra_pg_pass }} priv=ALL state=present login_user=postgres login_password={{ pg_pass }}
